services:
  app:
    container_name: rs-03-sample-flask-auth
    build:
      dockerfile: .devcontainer/Dockerfile
      context: ..
    volumes:
      - ..:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
