services:
  app:
    container_name: rs-03-sample-flask-auth
    build:
      dockerfile: .devcontainer/Dockerfile
      context: ..
    volumes:
      - ..:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'flask-crud'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - db-data:/var/lib/mysql
      
volumes:
  db-data: